using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectEuler.Problems
{
    /*
     Even Fibonacci numbers.
     Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     */
    class Problem2
    {
        internal static long EvenFibonacciNumbers(long limit)
        {
            long curr = 1, next = 2, temp=0,res=2;            
            while(true)
            {
                temp = next;
                next += curr;
                if (next > limit) break;
                curr = temp;                
                res = (next % 2 == 0) ? res + next : res;                
            }
            return res;
        }
    }
}
/*
i=2
temp=2,next=3,curr=2
i=3
temp=3,next=5,curr=3
i=4
temp=5,next=8,curr=5
i=5
temp=8,next=13,curr=8
i=6
temp=13,next=21,curr=13
i=7
temp=21,next=34,curr=21
i=8
temp=34,next=55,curr=34
i=9
temp=55,next=89,curr=55
*/